[package]
name = "fontpm-new"
description = """
A package-manager like tool to install fonts.
"""
publish = false
repository = "https://github.com/tecc/fontpm"
keywords = ["fontpm", "fonts"]
categories = ["command-line-utilities", "multimedia", "web-programming"]
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
console = "0.16.1"
dialoguer = "0.12.0"
dirs = "6.0.0"
indicatif = "0.18.3"
serde = "1.0.228"
thiserror = "2.0.17"
toml = { version = "0.9.8", features = ["preserve_order"] }
toml_edit = { version = "0.23.7", features = ["serde"] }

[features]
default = ["source-google-fonts"]
source-google-fonts = []
