[package]
name = "fontpm-new"
description = """
A package-manager like tool to install fonts.
"""
publish = false
repository = "https://github.com/tecc/fontpm"
keywords = ["fontpm", "fonts"]
categories = ["command-line-utilities", "multimedia", "web-programming"]
version = "0.3.0"
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
base64 = "0.22.1"
clap = { version = "4.5", features = ["derive"] }
console = "0.16.1"
dashmap = "6.1.0"
dialoguer = "0.12.0"
dirs = "6.0.0"
futures-util = "0.3.31"
indicatif = "0.18.3"
relative-path = { version = "2.0.1", features = ["serde"] }
reqwest = { version = "0.12.24", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
sha2 = "0.11.0-rc.3"
thiserror = "2.0.17"
tokio = "1.48.0"
toml = { version = "0.9.8", features = ["preserve_order"] }
toml_edit = { version = "0.23.7", features = ["serde"] }

[features]
default = ["source-google-fonts"]
source-google-fonts = []
